/*
 *  Tags.h
 *  OniLevelTool
 *
 *  Created by Sam Marshall on 5/1/12.
 *  Copyright 2012 Sam Marshall. All rights reserved.
 *
 */

#include "OniTM.h"

#include "ABNA.h"
#include "AGQC.h"
#include "AGQG.h"
#include "AGQR.h"
#include "AISA.h"
#include "AKAA.h"
#include "AKBA.h"
#include "AKBP.h"
#include "AKEV.h"
#include "AKOT.h"
#include "AKVA.h"

#include "BINA.h"
// All the BINA subclasses will go here.

#include "CBPI.h"
#include "CBPM.h"
#include "CONS.h"
#include "CRSA.h"
#include "DOOR.h"
#include "DPge.h"
#include "ENVP.h"
#include "FILM.h"
#include "HPge.h"
#include "IGHH.h"
#include "IGPA.h"
#include "IGPG.h"
#include "IGSA.h"
#include "IGSt.h"
#include "Impt.h"
#include "IPge.h"
#include "Keyl.h"
#include "M3GA.h"
#include "M3GM.h"
#include "Mtrl.h"
#include "OBAN.h"
#include "OBOA.h"
#include "OFGA.h"
#include "ONCC.h"
/*#include "ONCP.h"
#include "ONCV.h"
#include "ONGS.h"
#include "ONIA.h"
#include "ONLD.h"
#include "ONLV.h"
#include "ONOA.h"
#include "ONSK.h"
#include "ONVL.h"
#include "ONWC.h"
#include "OPge.h"
#include "OSBD.h"
#include "OTIT.h"
#include "OTLF.h"
#include "PLEA.h"
#include "PNTA.h"
#include "PSpc.h"
#include "PSpL.h"
#include "PSUI.h"
#include "QTNA.h"
#include "SNDD.h"
#include "SUBT.h"
#include "TRAC.h"
#include "TRAM.h"
#include "TRAS.h"
#include "TRBS.h"
#include "TRCM.h"
#include "TRGA.h"
#include "TRGE.h"
#include "TRIA.h"
#include "TRIG.h"
#include "TRMA.h"
#include "TRSC.h"
#include "TRTA.h"
#include "TSFF.h"
#include "TSFL.h"
#include "TSFT.h"
#include "TSGA.h"
#include "TURR.h"
#include "TXAN.h"
#include "TXCA.h"
#include "TXMA.h"
#include "TXMB.h"
#include "TXMP.h"
#include "TxtC.h"
#include "VCRA.h"
#include "WMCL.h"
#include "WMDD.h"
#include "WMM_.h"
#include "WMMB.h"
#include "WPge.h"

#include "AGDB.h"
#include "AITR.h"
#include "AKDA.h"
#include "OBDC.h"
#include "ONFA.h"
#include "ONMA.h"
#include "ONSA.h"
#include "ONTA.h"
#include "StNA.h"
#include "TStr.h"*/